### ISSUE TITLE
using paino audio through API

### ISSUE THREAD

**Issue by mohd7469** [MrLyfing/piano-js#1]
Hey

Saw this little cool thing suddenly that's awesome

It would better if the same piano audio can be accessible through a rest api which accept combination or array of alphabets **e.g: [ 'a', 'b', 'c', 'd' ... ]** as a payload and returns the relevant chords as an audio buffer 

Thanks

**Comment by peng-hf** [comment]
@awais786327 Thank you for your suggestion!
Unfortunately, this project was developed for learning purpose using only client-side technologies  :) But feel free to fork it and implemented your changes on top if needed.
